language: node_js
node_js:
  - '10'
# services:
#   - xvfb
before_script:
  - npm i
jobs:
  include:
    - stage: test
      os: linux
      addons:
        firefox: latest
        # chrome: stable
      before_script:
        - 'export DISPLAY=:99.0'
        - 'sh -e /etc/init.d/xvfb start'
      script: npm test
    - stage: test
      before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
      env: BROWSER=safari
      os: osx
      script: npx grunt test
    - stage: test
      os: windows
      script: npx grunt test
